all solutions
mixdone/haskell-hw pull request #3
Opened 2022-10-10 09:36 UTC by mixdone

2022-10-13 14:53 UTC, ghB111 requested changes

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +ml x y n = ml (pls x n) (dec y) n
лучше прятать такую функцию в where, так сразу будет понятно, где она и зачем применяется

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +ml x y n = ml (pls x n) (dec y) n
ну и проще это, конечно, сразу рекурсией реализовать
```haskell
mlt _ 0 = 0 
mlt x y = pls x $ mlt x (dec y)
```
меньше строчек -- меньше багов
другое дело, конечно, что умножение нуля на что-то сразу не вырезается, но это уже философия "читаемость vs эффективность"

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +          | x > y = y
Я полагаю, что (>) нельзя было использовать, но это не критично. Отпиши в комменты, как реализовать, используя разницу и равенство, не используя (>) или (<)

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +
то же про where

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +
тут тоже лучше nd спрятать

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +
идея здесь верная, но что-то не сходится. оператор минимизации (первый) должен брать 2 аргумента -- двуместную функцию и один параметр. Потом оператор минимизации закрепляет переданный параметр и перебирает второй параметр. Тут метод берет пару лишних `Int`ов

2022-10-13 14:53 UTC, ghB111 commented on month.hs
> +  f = (\i x1 x2 -> (mns2 x1 x2 (i+1)))
Ну да, тут можно поправить так, чтобы обойтись только оператором минимизации

2022-10-13 14:54 UTC, ghB111 commented
Поправь минимизацию и последние две функции и я приму, остальное все окей 👍

2022-10-15 04:41 UTC, mixdone commented on month.hs
> +          | x > y = y
Исользуя минус, если равно 0 - тогда одно, если нет - другое. Используя описанную функцию минуса.

2022-10-19 14:51 UTC, ghB111 commented on month.hs
> +          | x > y = y
Верно. Как там с минимизацией? Если добавишь минимизацию до семинара, в ведомость пойдет отл

2022-10-19 14:51 UTC, ghB111 commented on month.hs
> +          | x > y = y
Ну либо покажешь на семинаре

2023-03-02 12:06 UTC, merged