5 pack
mixdone/haskell-hw pull request #5
Opened 2022-10-27 10:35 UTC by mixdone

2022-11-01 15:04 UTC, ghB111 commented
не  надо удалять старые задачи

2022-11-01 15:10 UTC, ghB111 requested changes
Все выглядит очень хорошо, я жду от тебя задачу про собак, поправку в твой список и ответ на контрольный вопрос

2022-11-01 15:10 UTC, ghB111 commented on fiveComplesNumber.hs
> +complexSub a1 a2 = Comxplexnum ((realpart a1) - (realpart a2)) ((ipart a1) - (ipart a2))
тут проще запаттерн-матчить, чем повторять код
```haskell
complexSum (ComplexNum r1 i1) (ComplexNum r2 i2) = ComplexNum (r1 + r2) (i1 + i2)
```

2022-11-01 15:10 UTC, ghB111 commented on fivelist.hs
> +  deriving (Show, Eq)
Давай контрольный вопрос. У тебя в строчке 1 три раза встретилось 'MyList'. Все ли означают одинаковую сущность, и если нет -- кто какую

2022-11-01 15:10 UTC, ghB111 commented on fivelist.hs
> +  foldr f base (MyList x xs) = f x $ foldr f base xs
это действительно правая свертка 👍

2022-11-01 15:10 UTC, ghB111 commented on fivelist.hs
> +--mapMyList (\x -> x*2) (MyList 2 (MyList 3 (MyList 4 EmptyList)))
Здесь вообще  красота, конечно. Все через свертку работает. Отлично!
Единственное, к чему можно придраться -- toList не очень эффективно строит список. Чтобы построить быстрее. Можно собрать его задом-наперед, а потом развернуть. Но не критично

2022-11-01 15:10 UTC, ghB111 commented on fivelist.hs
> +--mapMyList (\x -> x*2) (MyList 2 (MyList 3 (MyList 4 EmptyList)))
а ну и тут toList еще возвращает развернутый список. поправь тогда, пожалуйста

2022-11-20 07:20 UTC, mixdone commented on fivelist.hs
> +  deriving (Show, Eq)
Первый MyList это конструктор типа, второй - конструктор значения, а третий выступает в роли рекурсивного обращения к типу

2022-12-01 05:15 UTC, ghB111 commented on fivelist.hs
> +  deriving (Show, Eq)
Да, все так. Третья и первая сущность означают одно и то же, т.е. оба конструкторы типа

2022-12-01 05:17 UTC, ghB111 approved these changes

2023-03-02 12:06 UTC, merged