Pack 7
mixdone/haskell-hw pull request #7
Opened 2022-12-08 09:33 UTC by mixdone

Unix2dos и dos2unix, работают неправильно, не могу понять почему, файл становится просто пустым.

2022-12-20 11:24 UTC, ghB111 requested changes
все отлично, пару вопросов только написал

2022-12-20 11:24 UTC, ghB111 commented on pack7.hs
> +  return (c1 == c2)
можно пример вызова?

2022-12-20 11:24 UTC, ghB111 commented on pack7.hs
> +  hClose fout
здесь очень хорошо. многие сделали просто печать в консоль. более, того тут еще pack.

Я знаю, что немного кисло за хорошее решение награждать дополнительными вопросами, но тут все-таки интересно: что делает pack и чем это выгоднее, чем операции над списками?

2022-12-20 11:24 UTC, ghB111 commented on pack7.hs
> +  return (c1 == c2)
тут тоже было бы хорошо пример вызова

2022-12-20 12:57 UTC, mixdone commented on pack7.hs
> +  return (c1 == c2)
Действительно, тут некорректно, из-за ленивости функция в итоге ломается. Закрывание файлов нужно убрать либо добавить какие-либо дейтвия с контентом файлов.

areEqualText "test.txt" "test.txt"
True

areEqualText "test.txt" "girlfriend.txt"
False

файл test.tst прикрепил, как пример. girlfriend.txt - файл из книги, тоже прикрепляю

2022-12-20 12:59 UTC, mixdone commented on pack7.hs
> +  return (c1 == c2)
Аналогичная ситуация...


*Main> areEqualBin "test.txt" "girlfriend.txt"
False
*Main> areEqualBin "test.txt" "test.txt"
True

2022-12-20 13:12 UTC, mixdone commented on pack7.hs
> +  hClose fout
На сколько я понимаю, тип данных текст это что-то среднее между строками и битовыми строками, и операции над текстом выполняются быстрее( хотя не все). В случае замены, она вроде реализрвана на основе мапа, а мап на тексте работает быстрее чем на списке, во всяком случае в лекции так было сказано (https://classroom.google.com/u/0/c/NTI3MDI3OTAzOTAz/m/NTc1MDQ3NjMwNjg4/details?hl=ru)

2022-12-20 13:41 UTC, ghB111 commented on pack7.hs
> +  return (c1 == c2)
да,  из-за ленивости ломается, все верно. починить можно либо использованием readFile (который является строгой функцией, т.е. она не ленивая), либо можно почитать  вот эту страницу в доках. прямо в начале показывается решение твоей проблемы https://hackage.haskell.org/package/deepseq-1.4.8.1/docs/Control-DeepSeq.html#v:deepseq

2022-12-20 13:47 UTC, ghB111 commented on pack7.hs
> +  hClose fout
По поводу мапы не  уверен, но да, там операции на Text должны быть обычно действительно быстрее

2022-12-20 13:47 UTC, ghB111 commented
Поправь ошибку с ленивостью любым способом и я засчитаю пак

2022-12-21 17:07 UTC, ghB111 approved these changes
👍

2023-03-02 12:07 UTC, merged